# Generated by Django 5.2.4 on 2025-07-07 18:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['timestamp']},
        ),
        migrations.AddField(
            model_name='chatgroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 7, 21, 42, 18, 585986)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatgroup',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
